### ISSUE TITLE
Mounts and user ids in docker-compose.yml

### ISSUE THREAD

**Issue by klpn** [snd-sweden/doris-storage-adapter#3]
The [Docker Compose YAML](https://github.com/snd-sweden/doris-storage-adapter/blob/main/docker-compose.yml) file will not work with a Docker Compose, for custom paths and storage in a POSIX filesystem, unless mounts mapping to the host filesystem are specified, and the uids and gids for the app user (1654) are synced with the users on the host. `Storage__FileSystemStorageService__BasePath` and `Storage__FileSystemStorageService__TempFilePath` refer to paths within the container.  E.g., assuming `/data/app/doris-{data,tmp}`  are created in the host filesystem and owned by the user with uid 1654 on the host.

```yaml
      - Storage__FileSystemStorageService__BasePath=/home/app/doris-data
      - Storage__FileSystemStorageService__TempFilePath=/home/app/doris-tmp
    volumes:
      - type: bind
        source: /data/app
        target: /home/app      
```
